#version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: dot_db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: lic_const_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - dot_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      #- app-network
      - nginx-proxy


  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_node
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
    - DB_HOST=db
    - DB_USER=root
    - DB_PASSWORD=12345
    - DB_NAME=lic_const_db
    - DB_PORT=3306
    - VIRTUAL_HOST=backdot.dotmunijalapa.org
    - LETSENCRYPT_HOST=backdot.dotmunijalapa.org
    - LETSENCRYPT_EMAIL=admin@dotmunijalapa.org

    networks:
      #- app-network
      - nginx-proxy

    depends_on:
      - db
    restart: always
    command: sh -c "while ! nc -z db 3306 ; do sleep 1 ; done && npm run start"
    #command: sh -c "while ! nc -z host.docker.internal 3306 ; do sleep 1 ; done && npm run dev"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_react
    ports: 
      - "5173:5173"
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    environment: 
      - VITE_BACKEND_URL=http://backend:3001
      - VIRTUAL_HOST=frontdot.dotmunijalapa.org
      - LETSENCRYPT_HOST=frontdot.dotmunijalapa.org
      - LETSENCRYPT_EMAIL=admin@dotmunijalapa.org

    networks: 
      #- app-network
      - nginx-proxy

    depends_on: 
      - backend
    restart: always

networks:
  # app-network:
  #   driver: bridge
  nginx-proxy:
    external: true
    
volumes:
  dot_data:




