#version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: dot_db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - dot_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - network_EPS-JFGL
      #- nginx-proxy


  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_node
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
    - DB_HOST=${DB_HOST}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - DB_PORT=${DB_PORT}
    # - VIRTUAL_HOST=back_dot.dotmunijalapa.org
    # - LETSENCRYPT_HOST=back_dot.dotmunijalapa.org
    # - LETSENCRYPT_EMAIL=admin@dotmunijalapa.org

    networks:
      - network_EPS-JFGL
      #- nginx-proxy

    depends_on:
      - db
    restart: always
    command: sh -c "while ! nc -z db 3306 ; do sleep 1 ; done && npm run start"
    #command: sh -c "while ! nc -z host.docker.internal 3306 ; do sleep 1 ; done && npm run dev"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_react
    ports: 
      - "5173:5173"
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    environment: 
      - VITE_BACKEND_URL=http://backend:3001
      # - VIRTUAL_HOST=front_dot.dotmunijalapa.org
      # - LETSENCRYPT_HOST=front_dot.dotmunijalapa.org
      # - LETSENCRYPT_EMAIL=admin@dotmunijalapa.org

    networks: 
      - network_EPS-JFGL
      #- nginx-proxy

    depends_on: 
      - backend
    restart: always

networks:
  network_EPS-JFGL:
   #nginx-proxy:
    external: true
    #driver: bridge

volumes:
  dot_data:




