-- DROP DATABASE lic_const_db;
-- CREATE DATABASE lic_const_db;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
CREATE DATABASE IF NOT EXISTS lic_const_db; 
USE lic_const_db;

-- Tabla: ROL
CREATE TABLE ROL (
  id_rol INT NOT NULL PRIMARY KEY
);

-- Tabla: ROL_NOMBRE
CREATE TABLE ROL_NOMBRE (
  ROL_id_rol INT NOT NULL,
  sexo ENUM('M', 'F') NOT NULL,
  nombre_rol VARCHAR(45) NOT NULL,
  PRIMARY KEY (ROL_id_rol, sexo),
  CONSTRAINT fk_ROL_NOMBRE_ROL1
    FOREIGN KEY (ROL_id_rol)
    REFERENCES ROL (id_rol)
);

-- Tabla: USUARIOS
CREATE TABLE USUARIOS (
  id_usuario INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  titulo VARCHAR(20) NULL,
  fecha_nacimiento DATE NOT NULL,
  correo VARCHAR(100) NOT NULL UNIQUE,
  contrasena VARCHAR(255) NOT NULL,
  es_contrasena_temporal BIT (1) NOT NULL DEFAULT 0, 
  fecha_registro DATETIME NOT NULL,
  fecha_de_baja DATETIME NULL,
  unidad ENUM('LICENCIAS DE CONSTRUCCION', 'DIRECCION DE ORDENAMIENTO TERRITORIAL Y DESARROLLO MUNICIPAL') NOT NULL,
  en_funciones BIT(1) NOT NULL,
  sexo ENUM('M', 'F') NOT NULL,
  ROL_id_rol INT NOT NULL,
  CONSTRAINT fk_USUARIOS_ROL1
    FOREIGN KEY (ROL_id_rol)
    REFERENCES ROL (id_rol)
);

-- Tabla: PROPIETARIOS
CREATE TABLE PROPIETARIOS (
  cui BIGINT(15) NOT NULL PRIMARY KEY,
  nombre_propietario VARCHAR(100) NOT NULL
);

-- Tabla: TASAS
CREATE TABLE TASAS (
  id_tasa INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fecha_emisionT DATE NOT NULL,
  direccion_propiedad VARCHAR(250) NOT NULL,
  alineacion_urban BIT(1) NOT NULL,
  anotaciones VARCHAR(45) NULL,
  cant_dem_movTierra DECIMAL (5,2) NULL,
  presupuesto_obra DECIMAL (10,2) NOT NULL,
  cantidad_cancelar DECIMAL (10,2) NOT NULL,
  documento BLOB NULL,
  latitud DECIMAL(10,8) NULL,
  longitud DECIMAL(11,8) NULL,
  PROPIETARIOS_cui BIGINT(15) NOT NULL,
  LICENCIAS_id_licencia_original INT NULL,
  LICENCIAS_fecha_emisionL_original DATE NULL,
  CONSTRAINT fk_TASAS_PROPIETARIOS1
    FOREIGN KEY (PROPIETARIOS_cui)
    REFERENCES PROPIETARIOS (cui),
  CONSTRAINT fk_TASAS_LICENCIAS1
    FOREIGN KEY (LICENCIAS_id_licencia_original, LICENCIAS_fecha_emisionL_original)
    REFERENCES LICENCIAS (id_licencia, fecha_emisionL)
);

-- Tabla: LICENCIAS
CREATE TABLE LICENCIAS (
  id_licencia INT NOT NULL,
  boleta_pago VARCHAR(45) NULL,
  fecha_emisionL DATE NOT NULL,
  fecha_vencimiento DATE NOT NULL,
  estado ENUM('PENDIENTE', 'ACTIVO', 'VENCIDO') NOT NULL,
  rotulo ENUM('50', '100', 'Razonado') NOT NULL,
  documento BLOB NULL,
  TASAS_id_tasa INT NOT NULL,
  LICENCIAS_id_licencia_ampliacion INT NULL,
  LICENCIAS_fecha_emisionL_ampliacion DATE NULL,
  PRIMARY KEY (id_licencia, fecha_emisionL),
  CONSTRAINT fk_LICENCIAS_TASAS1
    FOREIGN KEY (TASAS_id_tasa)
    REFERENCES TASAS (id_tasa),
  CONSTRAINT fk_LICENCIAS_LICENCIAS1
    FOREIGN KEY (LICENCIAS_id_licencia_ampliacion, LICENCIAS_fecha_emisionL_ampliacion)
    REFERENCES LICENCIAS (id_licencia, fecha_emisionL)
);

-- Tabla: TIPO_NOMENCLATURA
CREATE TABLE TIPO_NOMENCLATURA (
  id_tipoNomenclatura INT NOT NULL PRIMARY KEY,
  tipo_nomenclatura VARCHAR(45) NOT NULL
);

-- Tabla: NOMENCLATURAS
CREATE TABLE NOMENCLATURAS (
  id_nomenclatura INT NOT NULL,
  fecha_emisionN DATE NOT NULL,
  fecha_vencimientoN DATE NOT NULL,
  direccion_solici VARCHAR(250) NOT NULL,
  documento BLOB NULL,
  PROPIETARIOS_cui BIGINT(15) NOT NULL,
  TIPO_NOMENCLATURA_id_tipoNomenclatura INT NOT NULL,
  USUARIOS_id_usuario_firma INT NOT NULL,
  PRIMARY KEY (id_nomenclatura, fecha_emisionN, TIPO_NOMENCLATURA_id_tipoNomenclatura),
  CONSTRAINT fk_NOMENCLATURAS_PROPIETARIOS1
    FOREIGN KEY (PROPIETARIOS_cui)
    REFERENCES PROPIETARIOS (cui),
  CONSTRAINT fk_NOMENCLATURAS_TIPO_NOMENCLATURA1
    FOREIGN KEY (TIPO_NOMENCLATURA_id_tipoNomenclatura)
    REFERENCES TIPO_NOMENCLATURA (id_tipoNomenclatura),
  CONSTRAINT fk_NOMENCLATURAS_USUARIOS1
    FOREIGN KEY (USUARIOS_id_usuario_firma)
    REFERENCES USUARIOS (id_usuario)
);

-- Tabla: HISTORIAL_CAMBIOS
CREATE TABLE HISTORIAL_CAMBIOS (
  id_cambios INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fecha_hora DATETIME NOT NULL,
  USUARIOS_id_usuario INT NOT NULL,
  CONSTRAINT fk_HISTORIAL_CAMBIOS_USUARIOS1
    FOREIGN KEY (USUARIOS_id_usuario)
    REFERENCES USUARIOS (id_usuario)
);

-- Tabla: TIPO_CONSTRUCCION_TARIFA
CREATE TABLE TIPO_CONSTRUCCION_TARIFA (
  id_tipoConstruccion INT NOT NULL PRIMARY KEY,
  tipo_construccion VARCHAR(200) NOT NULL
);
-- ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- Tabla: TARIFA
CREATE TABLE TARIFA (
  id_nombreTarifa INT NOT NULL PRIMARY KEY,
  nombre_tarifa VARCHAR(200) NOT NULL,
  TIPO_CONSTRUCCION_TARIFA_id_tipoConstruccion INT NOT NULL,
  CONSTRAINT fk_NOMBRE_TARIFA_TIPO_CONSTRUCCION_TARIFA1
    FOREIGN KEY (TIPO_CONSTRUCCION_TARIFA_id_tipoConstruccion)
    REFERENCES TIPO_CONSTRUCCION_TARIFA (id_tipoConstruccion)
);
-- ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

-- Tabla: RECURSOS
CREATE TABLE RECURSOS (
  id_recursos INT NOT NULL PRIMARY KEY,
  nombre_pagina VARCHAR(45) NOT NULL,
  ruta_pagina VARCHAR(250) NOT NULL
);

-- Tabla: PERMISOS
CREATE TABLE PERMISOS (
  id_permiso INT NOT NULL PRIMARY KEY,
  acceso BIT(1) NOT NULL,
  ROL_id_rol INT NOT NULL,
  RECURSOS_id_recursos INT NOT NULL,
  CONSTRAINT fk_PERMISOS_ROL1
    FOREIGN KEY (ROL_id_rol)
    REFERENCES ROL (id_rol),
  CONSTRAINT fk_PERMISOS_RECURSOS1
    FOREIGN KEY (RECURSOS_id_recursos)
    REFERENCES RECURSOS (id_recursos)
);

-- Tabla: TASAS_TARIFA
CREATE TABLE TASAS_TARIFA (
  tarifa_correlativo INT NOT NULL,
  TASAS_id_tasa INT NOT NULL,
  dimension_construccion DECIMAL (5,2) NULL, 
  formula VARCHAR(250) NOT NULL,
  valor DECIMAL NOT NULL,
  TARIFA_id_nombreTarifa INT NOT NULL,
   PRIMARY KEY (TASAS_id_tasa, tarifa_correlativo, TARIFA_id_nombreTarifa),
  CONSTRAINT fk_TASAS_has_TARIFA_TASAS1
    FOREIGN KEY (TASAS_id_tasa)
    REFERENCES TASAS (id_tasa),
  CONSTRAINT fk_TASAS_has_TARIFA_TARIFA1
    FOREIGN KEY (TARIFA_id_nombreTarifa)
    REFERENCES TARIFA (id_nombreTarifa)
);


-- Tabla: TARIFA_COSTO_DIMENSION
CREATE TABLE TARIFA_COSTO_DIMENSION (
  TARIFA_id_nombreTarifa INT NOT NULL PRIMARY KEY,
  costo_tarifa DOUBLE NOT NULL,
  unidad_medida VARCHAR(10) NOT NULL,
  porcentaje DECIMAL(5,2) NOT NULL,
  CONSTRAINT fk_TARIFA_COSTO_DIMENSION_TARIFA1
    FOREIGN KEY (TARIFA_id_nombreTarifa)
    REFERENCES TARIFA (id_nombreTarifa)
);

-- Tabla: TARIFA_COSTO_PROYECTO
CREATE TABLE TARIFA_COSTO_PROYECTO (
  TARIFA_id_nombreTarifa INT NOT NULL PRIMARY KEY,
  porcentaje_costoProyecto DECIMAL(5,2) NOT NULL,
  porcentaje DECIMAL(5,2) NOT NULL,
  CONSTRAINT fk_TARIFA_COSTO_PROYECTO_TARIFA1
    FOREIGN KEY (TARIFA_id_nombreTarifa)
    REFERENCES TARIFA (id_nombreTarifa)
);

CREATE TABLE TASAS_TARIFA_VARIOS_NIVELES (
  TASAS_TARIFA_TASAS_id_tasa INT NOT NULL,
  TASAS_TARIFA_tarifa_correlativo INT NOT NULL,
  TASAS_TARIFA_TARIFA_id_nombreTarifa INT NOT NULL,
  nivel INT NOT NULL,
  dimension_construccion DECIMAL(5,2) NULL,
  formula VARCHAR(250) NOT NULL,
  valor DECIMAL NOT NULL,
  PRIMARY KEY (TASAS_TARIFA_TASAS_id_tasa, TASAS_TARIFA_tarifa_correlativo, TASAS_TARIFA_TARIFA_id_nombreTarifa, nivel),
  CONSTRAINT fk_TASAS_TARIFA_VARIOS_NIVELES_TASAS_TARIFA1
    FOREIGN KEY (TASAS_TARIFA_TASAS_id_tasa, TASAS_TARIFA_tarifa_correlativo, TASAS_TARIFA_TARIFA_id_nombreTarifa)
    REFERENCES TASAS_TARIFA (TASAS_id_tasa, tarifa_correlativo, TARIFA_id_nombreTarifa)
);

-- Tabla: USUARIO_FIRMA
CREATE TABLE USUARIO_FIRMA (
  USUARIOS_id_usuario INT NOT NULL,
  LICENCIAS_id_licencia INT NOT NULL,
  LICENCIAS_fecha_emisionL DATE NOT NULL,
  PRIMARY KEY (USUARIOS_id_usuario, LICENCIAS_id_licencia, LICENCIAS_fecha_emisionL),
  CONSTRAINT fk_USUARIOS_has_LICENCIAS_USUARIOS1
    FOREIGN KEY (USUARIOS_id_usuario)
    REFERENCES USUARIOS (id_usuario),
  CONSTRAINT fk_USUARIOS_has_LICENCIAS_LICENCIAS1
    FOREIGN KEY (LICENCIAS_id_licencia, LICENCIAS_fecha_emisionL)
    REFERENCES LICENCIAS (id_licencia, fecha_emisionL)
);

-- Tabla: HISTORIAL_TASAS
CREATE TABLE HISTORIAL_TASAS (
  HISTORIAL_CAMBIOS_id_cambios INT NOT NULL,
  TASAS_id_tasa INT NOT NULL,
  fecha_emisionT DATE NOT NULL,
  direccion_propiedad VARCHAR(250) NOT NULL,
  alineacion_urban BIT(1) NOT NULL,
  anotaciones VARCHAR(45) NULL,
  cant_dem_movTierra DECIMAL NULL,
  presupuesto_obra DOUBLE NOT NULL,
  cantidad_cancelar DOUBLE NOT NULL,
  latitud DECIMAL(10,8) NULL,
  longitud DECIMAL(11,8) NULL,
  tipo_cambio ENUM('CREACION', 'EDICION', 'ELIMINACION') NULL,
  PRIMARY KEY (HISTORIAL_CAMBIOS_id_cambios, TASAS_id_tasa),
  CONSTRAINT fk_HISTORIAL_TASAS_HISTORIAL_CAMBIOS1
    FOREIGN KEY (HISTORIAL_CAMBIOS_id_cambios)
    REFERENCES HISTORIAL_CAMBIOS (id_cambios),
  CONSTRAINT fk_HISTORIAL_TASAS_TASAS1
    FOREIGN KEY (TASAS_id_tasa)
    REFERENCES TASAS (id_tasa)
);

-- Tabla: HISTORIAL_TASAS_TARIFA
CREATE TABLE HISTORIAL_TASAS_TARIFA (
  HISTORIAL_CAMBIOS_id_cambios INT NOT NULL,
  TASAS_TARIFA_TASAS_id_tasa INT NOT NULL,
  TASAS_TARIFA_tarifa_correlativo INT NOT NULL,
  TASAS_TARIFA_TARIFA_id_nombreTarifa INT NOT NULL,
  dimension_construccion DECIMAL NULL,
  formula VARCHAR(250) NOT NULL,
  valor DECIMAL NOT NULL,
   PRIMARY KEY (HISTORIAL_CAMBIOS_id_cambios, TASAS_TARIFA_TASAS_id_tasa, TASAS_TARIFA_tarifa_correlativo, TASAS_TARIFA_TARIFA_id_nombreTarifa),
  CONSTRAINT fk_HISTORIAL_TASAS_TARIFA_HISTORIAL_CAMBIOS1
    FOREIGN KEY (HISTORIAL_CAMBIOS_id_cambios)
    REFERENCES HISTORIAL_CAMBIOS (id_cambios),
  CONSTRAINT fk_HISTORIAL_TASAS_TARIFA_TASAS_TARIFA1
     FOREIGN KEY (TASAS_TARIFA_TASAS_id_tasa, TASAS_TARIFA_TARIFA_correlativo, TASAS_TARIFA_TARIFA_id_nombreTarifa)
     REFERENCES TASAS_TARIFA (TASAS_id_tasa, tarifa_correlativo, TARIFA_id_nombreTarifa)
);

-- Tabla: HISTORIAL_LICENCIAS
CREATE TABLE HISTORIAL_LICENCIAS (
  LICENCIAS_id_licencia INT NOT NULL,
  LICENCIAS_fecha_emisionL DATE NOT NULL,
  HISTORIAL_CAMBIOS_id_cambios INT NOT NULL,
  fecha_vencimiento DATE NOT NULL,
  estado ENUM('PENDIENTE', 'ACTIVO', 'VENCIDO') NOT NULL,
  rotulo ENUM('50', '100', 'RAZONADO') NOT NULL,
  PRIMARY KEY (LICENCIAS_id_licencia, LICENCIAS_fecha_emisionL, HISTORIAL_CAMBIOS_id_cambios),
  CONSTRAINT fk_HISTORIAL_LICENCIAS_LICENCIAS1
    FOREIGN KEY (LICENCIAS_id_licencia, LICENCIAS_fecha_emisionL)
    REFERENCES LICENCIAS (id_licencia, fecha_emisionL),
  CONSTRAINT fk_HISTORIAL_LICENCIAS_HISTORIAL_CAMBIOS1
    FOREIGN KEY (HISTORIAL_CAMBIOS_id_cambios)
    REFERENCES HISTORIAL_CAMBIOS (id_cambios)
);

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

